---

- name: install runit
  apt: 
    name="runit"
    state="present"

- name: runsvdir service
  service: 
    name="{{runit_service_name[ansible_distribution_release] | default('runsvdir') }}"
    state="started"

# - name: Prepare config directories
#   file: 
#     state=directory
#     path="{{ item }}"
#   with_items:
#     - "{{ runit }}"
